cdm_search/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls'), name='index'),
    path('meas_lab/', include('meas_lab.urls'), name='meas_lab'),
    path('drug/', include('drug.urls'), name='drug'),
]

drug/urls.py
from django.urls import path
from . import views

app_name = 'drug'
urlpatterns = [
    path('', views.search_form, name='search_form'), # '/' in --> views.search_form
    path('results/', views.search, name='search'), # /results/ in --> views.search
]

index/urls.py
from django.urls import path
from . import views

app_name = 'index' 
urlpatterns = [
    path('', views.index_page, name='index_page'),
]

meas_lab/urls.py
from django.urls import path
from . import views

app_name = 'meas_lab'
urlpatterns = [
    path('', views.search_form, name='search_form'), # '/' in --> views.search_form
    path('results/', views.search, name='search'), # /results/ in --> views.search
]

drug/models.py
from django.db import models

# Create your models here.

index/models.py
from django.db import models

class Division(models.Model):
    name = models.CharField(max_length=30) # Measurement lab
    app_name = models.CharField(max_length=20) # meas_lab
    search_form = models.CharField(max_length=30) # meas_lab:search_form

    def __str__(self):
        return self.name

class Code(models.Model):
    division = models.ForeignKey('Division', on_delete=models.CASCADE) # Measurement.lab

    source_id = models.CharField(max_length=30) # L2101
    source_name = models.CharField(max_length=150) # WBC
    target_id = models.CharField(max_length=30) # 21929292
    target_name = models.CharField(max_length=150) # White blood cell [g/mL]
    vocabulary = models.CharField(max_length=30) # LOINC
    domain = models.CharField(max_length=30) # Measurement
    target_concept = models.CharField(max_length=30) # 20192-1
    unit = models.CharField(max_length=30) # g/mL
    review = models.CharField(max_length=250) # default
    other = models.CharField(max_length=100) # ?
   
    def __str__(self):
        return "%s -> %s" % (self.source_id, self.target_id)

drug/views.py
from django.shortcuts import render
from django.http import HttpResponse
from index.models import Code
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def search_form(request):
    if request.method == "GET":
        template = 'drug/search_form.html'
        return render(request, template)

    return HttpResponse('Search a valid manner.')

def search(request):
    template = "drug/search.html"
    query = request.GET.get('q')
    page = request.GET.get('page')
    if not page:
        page = 1
    if query:
        codes = Code.objects.filter(Q(division__name="Drug")
            & (Q(source_id__icontains=query)
            | Q(source_name__icontains=query)
            | Q(target_name__icontains=query)))
        if codes:
            paginator = Paginator(codes, 10)
            codes = paginator.get_page(page)
            context = {'codes': codes, 'q': query}
            return render(request, template, context)
        else:
            context = {'message': 'No results found.'}
            return render(request, template, context)
    else:
        context = {'message': 'You should at least search for something.'}
        return render(request, template, context)

index/views.py
from django.shortcuts import render, get_object_or_404
from .models import Code, Division

def index_page(request):
    codes = Code.objects.all()
    divisions = Division.objects.all()
    template = 'index/index_page.html'
    context = {'divisions': divisions}
    return render(request, template, context)

meas_lab/views.py
from django.shortcuts import render
from django.http import HttpResponse
from index.models import Code
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def search_form(request):
    if request.method == "GET":
        template = 'meas_lab/search_form.html'
        return render(request, template)

    return HttpResponse('Search a valid manner.')

def search(request):
    template = "meas_lab/search.html"
    query = request.GET.get('q')
    page = request.GET.get('page')
    if not page:
        page = 1
    if query:
        codes = Code.objects.filter(Q(division__name="Measurement lab")
            & (Q(source_id__icontains=query)
            | Q(source_name__icontains=query)
            | Q(target_name__icontains=query)))
        if codes:
            paginator = Paginator(codes, 10)
            codes = paginator.get_page(page)
            context = {'codes': codes, 'q': query}
            return render(request, template, context)
        else:
            context = {'message': 'No results found.'}
            return render(request, template, context)
    else:
        context = {'message': 'You should at least search for something.'}
        return render(request, template, context)

cdm_search/templates/base.html
{% load static %}
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Custom css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

    <!-- Font -->
    <style>
        * { font-family: 'GodoM'; }
    </style>

    <title>CDM 용어 데이터베이스</title>
  </head>

  <body>
    <div class="container">
    <div class="page-header">
      <h2><a href="{% url 'index:index_page' %}"><img src="{% static 'images/snuh.png' %}" />CDM 용어 데이터베이스</a></h2>
    </div>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.ohdsi.org/data-standardization/the-common-data-model/" target="_blank">OMOP CDM 설명</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              매핑 테이블
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'meas_lab:search_form' %}">Measurement lab</a>
              <a class="dropdown-item" href="#">Measurement vital</a>
              <a class="dropdown-item" href="{% url 'drug:search_form' %}">Drug</a>
              <a class="dropdown-item" href="#">Specimen</a>
              <!--<div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>-->
            </div>
          </li>
        </ul>
        <!--
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        -->
      </div>
    </nav>

    {% block content %}
    {% endblock %}
    </div>   

    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

drug/templates/drug/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="jumbotron vertical-center jumbotron-drug">
    <div class="jumbotron-text">
      <h1>Drug</h1>
      <p>Search란에 용어ID, 용어명 등의 검색어를 입력해주세요.</p>
    </div>
  </div>

  <form class="form-inline" action="{% url 'drug:search' %}" method="GET">
      <input class="form-control mr-sm-2" type="search" value="{{ request.GET.q }}" name="q" placeholder="예시: MTX 혹은 Syringe">
      <button class="btn btn-success" type="submit">Search</button>
  </form>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">SNUH 코드</th>
        <th scope="col">SNUH 코드명</th>
        <th scope="col">CDM 코드명</th>
        <th scope="col">CDM 코드</th>
        <th scope="col">Domain</th>
        <th scope="col">Vocabulary</th>
        <th scope="col">Review</th>
      </tr>
    </thead>
    <tbody>
      {% if message %}
      <th class="search-message" colspan="7">{{ message }}</th>
      {% else %}
        {% for code in codes.object_list %}
          <tr>
            <td>{{ code.source_id }}</td>
            <td>{{ code.source_name }}</td>
            <td>{{ code.target_name }}</td>
            <td>{{ code.target_id }}</td>
            <td>{{ code.domain }}</td>
            <td>{{ code.vocabulary }}</td>
            <td>{{ code.review }}</td>
          </tr>
        {% endfor %}
      {% endif %}
    </tbody>
  </table>

  <div class="pagination">
    <span class="step-links">
      {% if codes.has_previous %}
        <a href="?page=1&q={{ q }}">&laquo; first</a>
        <a href="?page={{ codes.previous_page_number }}&q={{ q }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ codes.number }} of {{ codes.paginator.num_pages }}.
      </span>

      {% if codes.has_next %}
        <a href="?page={{ codes.next_page_number }}&q={{ q }}">next</a>
        <a href="?page={{ codes.paginator.num_pages }}&q={{ q }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
{% endblock %}

drug/templates/drug/search_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="jumbotron vertical-center jumbotron-drug">
    <div class="jumbotron-text">
      <h1>Drug</h1>
      <p>Search란에 용어ID, 용어명 등의 검색어를 입력해주세요.</p>
    </div>
  </div>

  <form class="form-inline" action="{% url 'drug:search' %}" method="GET">
    <input class="form-control mr-sm-2" type="search" value="{{ request.GET.q }}" name="q" placeholder="예시: MTX 혹은 Syringe">
    <button class="btn btn-success" type="submit">Search</button>
  </form>

{% endblock %}

index/templates/index/index_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="jumbotron vertical-center">
    <div class="jumbotron-text">
      <h1>Hello World!</h1>
      <p>CDM 용어 매핑 테이블 탐색을 지원합니다.<br>CDM 용어 매핑 테이블 중 하나를 선택해주세요.</p>
    </div>
  </div>
<!--
  {% for division in divisions %}
  <div>
    {% if division.app_name == "meas_lab" %}
      <a href="{% url 'meas_lab:search_form' %}">{{ division }}</a>
    {% elif division.app_name != "meas_lab" %}
      <a href="{% url 'meas_lab:search_form' %}">{{ division }}</a>
    {% endif %}
  </div>
  {% endfor %}
-->
{% endblock %}

meas_lab/templates/meas_lab/search.html
{% extends 'base.html' %}

{% block content %}

  <div class="jumbotron vertical-center jumbotron-meas-lab">
    <div class="jumbotron-text">
      <h1>Measurement lab</h1>
      <p>Search란에 용어ID, 용어명 등의 검색어를 입력해주세요.</p>
    </div>
  </div>

  <form class="form-inline" action="{% url 'meas_lab:search' %}" method="GET">
      <input class="form-control mr-sm-2" type="search" value="{{ request.GET.q }}" name="q" placeholder="예시: L200 혹은 White">
      <button class="btn btn-success" type="submit">Search</button>
  </form>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">SNUH 코드</th>
        <th scope="col">SNUH 코드명</th>
        <th scope="col">CDM 코드명</th>
        <th scope="col">CDM 코드</th>
        <th scope="col">Domain</th>
        <th scope="col">Vocabulary</th>
        <th scope="col">Review</th>
      </tr>
    </thead>
    <tbody>
      {% if message %}
      <th class="search-message" colspan="7">{{ message }}</th>
      {% else %}
        {% for code in codes.object_list %}
          <tr>
            <td>{{ code.source_id }}</td>
            <td>{{ code.source_name }}</td>
            <td>{{ code.target_name }}</td>
            <td>{{ code.target_id }}</td>
            <td>{{ code.domain }}</td>
            <td>{{ code.vocabulary }}</td>
            <td>{{ code.review }}</td>
          </tr>
        {% endfor %}
      {% endif %}
    </tbody>
  </table>

  <div class="pagination">
    <span class="step-links">
      {% if codes.has_previous %}
        <a href="?page=1&q={{ q }}">&laquo; first</a>
        <a href="?page={{ codes.previous_page_number }}&q={{ q }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ codes.number }} of {{ codes.paginator.num_pages }}.
      </span>

      {% if codes.has_next %}
        <a href="?page={{ codes.next_page_number }}&q={{ q }}">next</a>
        <a href="?page={{ codes.paginator.num_pages }}&q={{ q }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
{% endblock %}

meas_lab/templates/meas_lab/search_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="jumbotron vertical-center jumbotron-meas-lab">
    <div class="jumbotron-text">
      <h1>Measurement lab</h1>
      <p>Search란에 용어ID, 용어명 등의 검색어를 입력해주세요.</p>
    </div>
  </div>

  <form class="form-inline" action="{% url 'meas_lab:search' %}" method="GET">
    <input class="form-control mr-sm-2" type="search" value="{{ request.GET.q }}" name="q" placeholder="예시: L200 혹은 White">
    <button class="btn btn-success" type="submit">Search</button>
  </form>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Search: CDM Table{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
      .page-header {
        margin-top: 0;
      }
    </style>
  </head>
  <body>
    {% include 'header.html' %}
    <div class="container">

      {% block content %}
      {% endblock %}

    </div>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

templates/header.html
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Search through Measurement (진단검사)</a>
    </div>
    <div class="collapse navbar-collapse" id="main-menu">
      <ul class="nav navbar-nav">
        <li{% if '/search/' in request.path %} class="active"{% endif %}>
          <a href="{% url 'search' %}">Search</a>
        </li>
      </ul>
    </div>
  </div>
</nav>